#!/usr/bin/env bash
# Release helper: tag source, build bright-vision-core (cecli + bright_vision_core) for PyPI,
# then commit generated version metadata.
#
# Order matters: setuptools-scm rewrites _version.py during/after build from the git
# tag. Committing version files *before* build leaves a dirty tree; we tag first, build,
# sync metadata from the tag, then commit.
#
# Usage:
#   ./build.sh v0.90.10
#   ./build.sh v0.90.10 --no-upload
#   ./build.sh v0.90.10 --yes
#   ./build.sh v0.111.1.bright0 --rebuild-tag --yes --sync-vision  # publish + pin parent
#   ./build.sh --sync-only v0.111.1.bright0 --yes                  # pin parent only
#   Git .brightN tags -> PyPI 0.x.y.postN (scripts/scm_pep440.sh)
#
# Requires: git, python (PYTHON=python3.14), build, twine; PyPI credentials for upload.

set -euo pipefail

# Never source this script (set -e + failure exits your interactive zsh/bash).
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  echo "error: run as ./build.sh, do not source it" >&2
  return 1 2>/dev/null || exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

VERSION=""
UPLOAD=1
ASSUME_YES=0
SYNC_VISION=0
SYNC_ONLY=0
REBUILD_TAG=0
SYNC_FORCE_PIP=0

# Generated by setuptools-scm / editable install — committed after build, not before.
VERSION_FILES=(
  "bright_vision_core.egg-info/PKG-INFO"
  "bright_vision_core.egg-info/SOURCES.txt"
  "cecli/_version.py"
)

usage() {
  echo "Usage: $0 <version-tag> [--no-upload] [--yes] [--sync-vision] [--rebuild-tag]" >&2
  echo "       $0 --sync-vision <version-tag>   # pin parent bright-vision only" >&2
  echo "  version-tag   e.g. v0.90.10 or v0.90.9.bright0" >&2
  echo "  --sync-vision update bright-vision/requirements-core.txt and parent .venv" >&2
  echo "  --rebuild-tag build/upload from existing tag (no new tag); use after retagging" >&2
  exit 1
}

rebuild_from_existing_tag() {
  local wt="${ROOT}/.release-worktree"
  local tag_commit
  tag_commit="$(git rev-parse "$VERSION")"
  local pkg_name
  pkg_name="$(git show "${VERSION}:pyproject.toml" 2>/dev/null | sed -n 's/^name = "\(.*\)"/\1/p' | head -1)"
  echo "Building from tag ${VERSION} (${tag_commit})..."
  warn_ambiguous_bright_tags "$tag_commit"
  echo "  pyproject name: ${pkg_name:-unknown}"
  if [[ "${pkg_name}" != "bright-vision-core" ]]; then
    echo "warning: tag ${VERSION} does not package bright-vision-core (got: ${pkg_name})" >&2
    echo "  To ship Bright Vision Core as 0.100.0, move the tag to the bright-vision commit, e.g.:" >&2
    echo "    git tag -f v0.100.0 9e57750c5 && git push origin v0.100.0 --force" >&2
    confirm "Continue building ${pkg_name} anyway?" || die "aborted"
  fi

  rm -rf "$wt" "${ROOT}/dist"
  mkdir -p "${ROOT}/dist"
  git worktree add -f "$wt" "$VERSION"
  (
    cd "$wt"
    rm -rf dist build *.egg-info cecli_dev.egg-info bright_vision_core.egg-info
    apply_scm_pep440 "$wt" "$VERSION"
    "$PYTHON" -m pip install -q build
    "$PYTHON" -m build
    cp -f dist/* "${ROOT}/dist/"
  )
  git worktree remove -f "$wt" 2>/dev/null || rm -rf "$wt"

  echo "Artifacts:"
  ls -lh "${ROOT}/dist/"

  command -v twine >/dev/null 2>&1 || "$PYTHON" -m pip install -q twine
  "$PYTHON" -m twine check "${ROOT}/dist/"*

  if (( UPLOAD )); then
    echo "Uploading to PyPI..."
    if (( ASSUME_YES )); then
      "$PYTHON" -m twine upload "${ROOT}/dist/"*
    else
      confirm "Upload dist/* to PyPI?" || die "aborted before upload (artifacts in dist/)"
      "$PYTHON" -m twine upload "${ROOT}/dist/"*
    fi
    echo "Done. Published ${VERSION} (${pkg_name}) to PyPI."
  else
    echo "Done. Built dist/ for ${VERSION} (--no-upload)."
  fi

  if (( SYNC_VISION )); then
    echo ""
    if (( UPLOAD )); then
      SYNC_FORCE_PIP=1
    fi
    run_sync_vision
  fi
}

apply_scm_pep440() {
  local dir="${1:-$ROOT}"
  local tag="${2:-${VERSION:-}}"
  if [[ -f "${ROOT}/scripts/scm_pep440.sh" ]]; then
    # shellcheck disable=SC1091
    if [[ -n "$tag" ]]; then
      eval "$(sh "${ROOT}/scripts/scm_pep440.sh" "$dir" "$tag")"
    else
      eval "$(sh "${ROOT}/scripts/scm_pep440.sh" "$dir")"
    fi
    if [[ -n "${SETUPTOOLS_SCM_PRETEND_VERSION:-}" ]]; then
      echo "  setuptools-scm pretend: ${SETUPTOOLS_SCM_PRETEND_VERSION}"
    fi
  fi
}

warn_ambiguous_bright_tags() {
  local commit="$1"
  local tags
  tags="$(git tag --points-at "$commit" 2>/dev/null | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+\.bright[0-9]+$' || true)"
  local count=0
  if [[ -n "$tags" ]]; then
    count="$(printf '%s\n' "$tags" | wc -l | tr -d ' ')"
  fi
  if (( count > 1 )); then
    echo "warning: ${count} .brightN tags point at ${commit}; git describe alone is ambiguous." >&2
    printf '  %s\n' $tags >&2
    echo "  build.sh uses the tag you passed (${VERSION}) for PyPI version." >&2
  fi
}

run_sync_vision() {
  # Subprocess only — never source sync (and zsh ERR_EXIT will exit the tab if this returns 1).
  local -a sync_args=("${VERSION}")
  (( ASSUME_YES )) && sync_args+=(--yes)
  (( SYNC_FORCE_PIP )) && sync_args+=(--force-pip)
  bash "${ROOT}/scripts/sync_bright_vision.sh" "${sync_args[@]}"
}

die() {
  echo "error: $*" >&2
  exit 1
}

confirm() {
  local prompt="$1"
  if (( ASSUME_YES )); then
    return 0
  fi
  local ans
  read -r -p "${prompt} [y/N] " ans
  ans="$(printf '%s' "$ans" | tr '[:upper:]' '[:lower:]')"
  [[ "$ans" == "y" || "$ans" == "yes" ]]
}

porcelain_path() {
  local rest="${1:3}"
  rest="${rest#\"}"
  rest="${rest%\"}"
  if [[ "$rest" == *" -> "* ]]; then
    echo "${rest%% -> *}"
  else
    echo "${rest%% *}"
  fi
}

is_version_file() {
  local path="$1"
  local f
  for f in "${VERSION_FILES[@]}"; do
    [[ "$path" == "$f" ]] && return 0
  done
  return 1
}

sync_version_metadata_from_tag() {
  echo "Syncing version metadata from git tag ${VERSION}..."
  "$PYTHON" -m pip install -q "setuptools-scm[toml]>=8" build wheel

  # At the tagged commit, read version from git and write pyproject [tool.setuptools_scm] write_to.
  # setuptools-scm 8+ requires dump_version(root, version, write_to); use _get_version + Configuration.
  "$PYTHON" - <<'PY' || die "setuptools-scm could not read version from tag"
from setuptools_scm import Configuration, _get_version

config = Configuration.from_file(
    relative_to="pyproject.toml",
    dist_name="bright-vision-core",
)
version = _get_version(config)
if not version:
    raise SystemExit("setuptools-scm could not detect version (is the release tag on HEAD?)")
write_to = config.write_to or config.version_file
print(f"release version {version} -> {write_to}")
PY

  "$PYTHON" -m pip install -q -e . --no-deps
}

commit_version_metadata() {
  for f in "${VERSION_FILES[@]}"; do
    if [[ -e "$f" ]]; then
      git add "$f"
    else
      echo "warning: ${f} not found, skipping" >&2
    fi
  done

  if git diff --cached --quiet; then
    echo "No release metadata changes to commit."
    return 0
  fi

  local RELEASE_MSG="chore: release ${VERSION}"
  if (( ASSUME_YES )); then
    git commit -m "$RELEASE_MSG"
  elif confirm "Commit release metadata with message: \"${RELEASE_MSG}\"?"; then
    git commit -m "$RELEASE_MSG"
  else
    die "aborted before release metadata commit"
  fi
  echo "Committed release metadata (synced after build)."
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-upload) UPLOAD=0; shift ;;
    --yes) ASSUME_YES=1; shift ;;
    --sync-vision)
      SYNC_VISION=1
      shift
      ;;
    --sync-only)
      SYNC_ONLY=1
      SYNC_VISION=1
      shift
      ;;
    --rebuild-tag) REBUILD_TAG=1; shift ;;
    -h|--help) usage ;;
    -*)
      die "unknown option: $1"
      ;;
    *)
      [[ -z "$VERSION" ]] || die "unexpected extra argument: $1"
      VERSION="$1"
      shift
      ;;
  esac
done

[[ -n "$VERSION" ]] || usage

if (( SYNC_ONLY )); then
  run_sync_vision
  exit 0
fi

if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+([.-][0-9A-Za-z.]+)?$ ]]; then
  die "version must look like v0.90.10 or v0.90.9.bright0 (got: ${VERSION})"
fi

command -v git >/dev/null 2>&1 || die "git not found"
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "not a git repository"

PYTHON="${PYTHON:-python3.14}"
if ! command -v "$PYTHON" >/dev/null 2>&1; then
  PYTHON=python3
fi
command -v "$PYTHON" >/dev/null 2>&1 || die "python not found (set PYTHON=...)"

if git rev-parse "$VERSION" >/dev/null 2>&1; then
  if (( REBUILD_TAG )); then
    rebuild_from_existing_tag
    exit 0
  fi
  if (( SYNC_VISION )) && ! (( REBUILD_TAG )); then
    echo "Tag ${VERSION} already exists; syncing parent bright-vision only."
    run_sync_vision
    exit 0
  fi
  die "tag ${VERSION} already exists locally (use --rebuild-tag to publish it, or --sync-vision to pin parent only)"
fi

if git ls-remote --exit-code --tags origin "$VERSION" >/dev/null 2>&1; then
  if (( REBUILD_TAG )); then
    git fetch origin tag "$VERSION" --no-tags 2>/dev/null || true
    rebuild_from_existing_tag
    exit 0
  fi
  die "tag ${VERSION} already exists on origin (use --rebuild-tag to publish that tag)"
fi

BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$BRANCH" != "main" && "$BRANCH" != "master" ]]; then
  echo "warning: on branch '${BRANCH}', not main/master" >&2
  confirm "Continue anyway?" || die "aborted"
fi

echo "Checking for uncommitted changes..."
OTHER_LINES=()
while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  path="$(porcelain_path "$line")"
  is_version_file "$path" && continue
  OTHER_LINES+=("$line")
done < <(git status --porcelain 2>/dev/null || true)

if ((${#OTHER_LINES[@]} > 0)); then
  echo "Uncommitted changes outside generated version metadata:" >&2
  printf '  %s\n' "${OTHER_LINES[@]}" >&2
  echo >&2
  if (( ASSUME_YES )); then
    die "working tree is dirty; commit or stash other changes, or run without --yes"
  fi
  if confirm "Commit these changes now before release?"; then
    git add -A
    DEFAULT_MSG="chore: prepare ${VERSION}"
    if ! confirm "Use default commit message: \"${DEFAULT_MSG}\"?"; then
      read -r -p "Commit message: " COMMIT_MSG
      [[ -n "${COMMIT_MSG:-}" ]] || die "empty commit message"
    else
      COMMIT_MSG="$DEFAULT_MSG"
    fi
    git commit -m "$COMMIT_MSG"
    echo "Committed other changes."
  else
    die "aborted — commit or stash changes before releasing"
  fi
fi

# Discard local edits to generated files so the tag points at committed source only.
DIRTY_VERSION=()
while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  path="$(porcelain_path "$line")"
  is_version_file "$path" && DIRTY_VERSION+=("$path")
done < <(git status --porcelain 2>/dev/null || true)

if ((${#DIRTY_VERSION[@]} > 0)); then
  echo "Discarding local changes to generated version files before tag..."
  for f in "${VERSION_FILES[@]}"; do
    git restore --staged --worktree "$f" 2>/dev/null || true
  done
fi

# Tree must be clean before tag (generated files restored or already clean).
REMAINING=()
while IFS= read -r line; do
  [[ -z "$line" ]] && continue
  REMAINING+=("$line")
done < <(git status --porcelain 2>/dev/null || true)

if ((${#REMAINING[@]} > 0)); then
  echo "Working tree still dirty:" >&2
  printf '  %s\n' "${REMAINING[@]}" >&2
  die "commit or stash before releasing"
fi

echo "Tagging ${VERSION} on current commit (source only)..."
if (( ASSUME_YES )); then
  git tag "$VERSION"
else
  confirm "Create git tag ${VERSION}? (PyPI build will use this tag)" || die "aborted before tag"
  git tag "$VERSION"
fi

echo "Cleaning build artifacts..."
rm -rf dist build *.egg-info cecli_dev.egg-info bright_vision_core.egg-info

echo "Building sdist and wheel from tag ${VERSION}..."
apply_scm_pep440 "$ROOT"
"$PYTHON" -m pip install -q build
"$PYTHON" -m build

sync_version_metadata_from_tag
commit_version_metadata

echo "Pushing to origin..."
if (( ASSUME_YES )); then
  git push origin HEAD
  git push origin "$VERSION"
else
  confirm "Push branch ${BRANCH} and tag ${VERSION}?" || die "aborted before push"
  git push origin HEAD
  git push origin "$VERSION"
fi

if (( UPLOAD )); then
  command -v twine >/dev/null 2>&1 || "$PYTHON" -m pip install -q twine
  echo "Uploading to PyPI..."
  if (( ASSUME_YES )); then
    "$PYTHON" -m twine upload dist/*
  else
    confirm "Upload dist/* to PyPI?" || die "aborted before upload (artifacts in dist/)"
    "$PYTHON" -m twine upload dist/*
  fi
  echo "Done. Released ${VERSION} to PyPI."
  echo "Note: tag ${VERSION} is on the pre-metadata commit; main may be one commit ahead with synced _version.py."
else
  echo "Done. Built dist/ for ${VERSION} (--no-upload)."
fi

if (( SYNC_VISION )); then
  echo ""
  if (( UPLOAD )); then
    SYNC_FORCE_PIP=1
  fi
  run_sync_vision
fi
