source 'https://rubygems.org'

ruby '>= 3.3'

gem 'jekyll'
gem "just-the-docs", "0.8.2"
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem "webrick"
gem 'github-pages', group: :jekyll_plugins
gem "html-proofer"
